//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormFibonacci.XmlToJsonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lemonway.com/webservices", ConfigurationName="XmlToJsonService.XmlToJsonServiceSoap")]
    public interface XmlToJsonServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément xml de l'espace de noms http://lemonway.com/webservices n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lemonway.com/webservices/XmlToJson", ReplyAction="*")]
        WinFormFibonacci.XmlToJsonService.XmlToJsonResponse XmlToJson(WinFormFibonacci.XmlToJsonService.XmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lemonway.com/webservices/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<WinFormFibonacci.XmlToJsonService.XmlToJsonResponse> XmlToJsonAsync(WinFormFibonacci.XmlToJsonService.XmlToJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://lemonway.com/webservices", Order=0)]
        public WinFormFibonacci.XmlToJsonService.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(WinFormFibonacci.XmlToJsonService.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lemonway.com/webservices")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://lemonway.com/webservices", Order=0)]
        public WinFormFibonacci.XmlToJsonService.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(WinFormFibonacci.XmlToJsonService.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://lemonway.com/webservices")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(string XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XmlToJsonServiceSoapChannel : WinFormFibonacci.XmlToJsonService.XmlToJsonServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlToJsonServiceSoapClient : System.ServiceModel.ClientBase<WinFormFibonacci.XmlToJsonService.XmlToJsonServiceSoap>, WinFormFibonacci.XmlToJsonService.XmlToJsonServiceSoap {
        
        public XmlToJsonServiceSoapClient() {
        }
        
        public XmlToJsonServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlToJsonServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlToJsonServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlToJsonServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinFormFibonacci.XmlToJsonService.XmlToJsonResponse WinFormFibonacci.XmlToJsonService.XmlToJsonServiceSoap.XmlToJson(WinFormFibonacci.XmlToJsonService.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public string XmlToJson(string xml) {
            WinFormFibonacci.XmlToJsonService.XmlToJsonRequest inValue = new WinFormFibonacci.XmlToJsonService.XmlToJsonRequest();
            inValue.Body = new WinFormFibonacci.XmlToJsonService.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            WinFormFibonacci.XmlToJsonService.XmlToJsonResponse retVal = ((WinFormFibonacci.XmlToJsonService.XmlToJsonServiceSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WinFormFibonacci.XmlToJsonService.XmlToJsonResponse> WinFormFibonacci.XmlToJsonService.XmlToJsonServiceSoap.XmlToJsonAsync(WinFormFibonacci.XmlToJsonService.XmlToJsonRequest request) {
            return base.Channel.XmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WinFormFibonacci.XmlToJsonService.XmlToJsonResponse> XmlToJsonAsync(string xml) {
            WinFormFibonacci.XmlToJsonService.XmlToJsonRequest inValue = new WinFormFibonacci.XmlToJsonService.XmlToJsonRequest();
            inValue.Body = new WinFormFibonacci.XmlToJsonService.XmlToJsonRequestBody();
            inValue.Body.xml = xml;
            return ((WinFormFibonacci.XmlToJsonService.XmlToJsonServiceSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
